spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqul-db.c3wm6eg2sy5e.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    username: kangjy311@gmail.com
    address: kangjy311@gmail.com
    password: lggssttlrgixtsfs
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true


jwt:
  secret: ryHXPO6Bz0CyKFsFlFFzOgtUcbZG2uHZ2fYMEiBwVrN/cJy/jz/brqyHqZXu0wso